language: node_js
cache: yarn
node_js: '8'

before_install:
- yarn global add greenkeeper-lockfile@1

install:
- yarn

before_script:
- cp .env.example .env
- greenkeeper-lockfile-update

script:
- yarn run build

after_script:
- greenkeeper-lockfile-upload
